import = [
    "~/.config/alacritty/themes/themes/rose-pine.toml" # can change any theme from the git repo here
]

[window]
blur=true
opacity=0.7

[font]
normal = { family = "Source Code Pro", style = "Regular" }
